language: python
branches:
  except:
    - staging.tmp
    - trying.tmp
python:
  - "3.6"
cache: pip
services:
  - mysql
env:
  global:
    - mysql_user=root
  matrix:
    - CMD="python dev.py tests"
    - CMD="python dev.py mypy"
    - CMD="python dev.py lint"
    - CMD="isort --check-only"
install:
  - travis_retry pip install -r requirements.txt
script:
  - echo $CMD
  - $CMD
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
