language: python
branches:
  except:
    - staging.tmp
    - trying.tmp
python:
  - "3.6"
cache: pip
services:
  - mysql
env:
  global:
    - mysql_user=root slow_query=999.0
  matrix:
    - CMD="python dev.py tests"
    - CMD="python dev.py mypy"
    - CMD="python dev.py lint"
    - CMD="python dev.py jslint"
    - CMD="python dev.py isort"
install:
  - travis_retry pip install -r requirements.txt
  - npm install
  - npm run-script build
script:
  - echo $CMD
  - $CMD
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
